version: '3.8'

services:
  react-app:
    stdin_open: true
    tty: true
    image: albertkingdomdevelop/frontend
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.prod
    ports:
      - 80:80
    env_file:
      - ./.env