FROM node:16 as build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 3000
ENV REACT_APP_BACKEND_URL=http://ec2-35-76-111-131.ap-northeast-1.compute.amazonaws.com
RUN npm run build

FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html